### ISSUE TITLE
Separate build and publish actions

### ISSUE THREAD

**Issue by lance** [securesign/image-factory#14]
PR actions fail due to secrets not being available to forks. Let's split CI for this repo into two. For PRs, there is a build (and really there should be some kind of smoke tests, but that is not there yet). When the code lands on main i.e. the PR is merged, then there are both build and publish actions.

**Comment by cooktheryan** [comment]
@lance one strategy we could use is if statements that way we don't have to archive the images between actions

**Comment by lance** [comment]
> @lance one strategy we could use is if statements that way we don't have to archive the images between actions

That could work too. It might be easier to make the change sooner using that approach.
