### ISSUE TITLE
Use midstream forks instead of upstream for rekor, fulcio, etc

### ISSUE THREAD

**Issue by lance** [securesign/image-factory#3]
This ensures that we have control over the source being fed into the RH build systems, and allows us to patch upstream in the midstream forks.

**Comment by sallyom** [comment]
- [x] https://github.com/securesign/rekor
- [x] https://github.com/securesign/fulcio
- [x] https://github.com/securesign/timestamp-authority
- [x] https://github.com/securesign/scaffolding
- [x] https://github.com/securesign/helm-charts
- [x] https://github.com/cosign
- [x] https://github.com/securesign/gitsign
