### ISSUE TITLE
Versions of images within GitHub actions should be variables

### ISSUE THREAD

**Issue by cooktheryan** [securesign/image-factory#7]
We should use environment variables for the version of images that we create allowing for us to only make a chance in one section of the builds versus each individual section or in multiple places.

For example the fulcio image has the same version defined 3 times https://github.com/securesign/image-factory/blob/main/.github/workflows/image-factory.yaml#L26-L49

**Comment by tommyd450** [comment]
Is there anything being done for this issue or can I start messing around with it?
