### ISSUE TITLE
Modify fulcio build to utilize `release-next` branch in midstream

### ISSUE THREAD

**Issue by lance** [securesign/image-factory#9]
Similar to how the rekor image is now being built.

https://github.com/securesign/image-factory/blob/13d1e828c4ec5576089cf0a28e7f6f93232dac2c/.github/workflows/image-factory.yaml#L51-L92

**Comment by JasonPowr** [comment]
Im going to work on this issue :+1: , if thats ok?

**Comment by lance** [comment]
@JasonPowr that's great - thanks! I went ahead and assigned it to you.

**Comment by lance** [comment]
Fixed in https://github.com/securesign/image-factory/pull/11
